Convert service-setup to cron job
To prevent a service setup failure from not inserting config. Service setup runs every 5 minutes to maintain a constant config state.

diff --git a/deploy/templates/service-setup.yaml b/deploy/templates/service-setup.yaml
--- a/deploy/templates/service-setup.yaml
+++ b/deploy/templates/service-setup.yaml
@@ -2,150 +2,154 @@
 # upgraded. This Job pulls in an image with configuration to load into
 # the F+ services which is specific to deployment decisions made by ACS.
 apiVersion: batch/v1
-kind: Job
+kind: CronJob
 metadata:
   namespace: {{ .Release.Namespace }}
   # Give the job a random id so helm reruns it on helm upgrade.
-  name: service-setup-{{ randAlphaNum 8 | lower }}
+  name: service-setup
 spec:
-  backoffLimit: 9999
-  template:
+  concurrencyPolicy: Forbid
+  failedJobsHistoryLimit: 1
+  successfulJobsHistoryLimit: 1
+  schedule: "*/5 * * * *"  # Runs every 5 minutes
+  jobTemplate:
     spec:
-      serviceAccountName: service-setup
-      restartPolicy: OnFailure
-      volumes:
-        - name: git-checkouts
-          emptyDir: { }
-        - name: manager-keytab
-          secret:
-            secretName: manager-keytab
-        - name: krb5-conf
-          configMap:
-            name: krb5-conf
-        - name: manager-ccache-storage
-          emptyDir: { }
-      initContainers:
-        - name: service-setup
+      template:
+        spec:
+          serviceAccountName: service-setup
+          restartPolicy: OnFailure
+          volumes:
+            - name: git-checkouts
+              emptyDir: { }
+            - name: manager-keytab
+              secret:
+                secretName: manager-keytab
+            - name: krb5-conf
+              configMap:
+                name: krb5-conf
+            - name: manager-ccache-storage
+              emptyDir: { }
+          initContainers:
+            - name: service-setup
 {{ include "amrc-connectivity-stack.image" (list . .Values.serviceSetup) | indent 10 }}
-          env:
-            - name: DIRECTORY_URL
-              value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
-            - name: SERVICE_USERNAME
-              value: admin
-            - name: SERVICE_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: admin-password
-                  key: password
-            - name: VERBOSE
-              value: ALL,!token,!service
-            - name: GIT_CHECKOUTS
-              value: /data
-            - name: SS_CONFIG
-              value: {{ .Values.serviceSetup.config | toRawJson | quote }}
-            - name: ACS_CONFIG
-              value: {{
-                dict
-                  "organisation"    .Values.acs.organisation
-                  "namespace"       .Release.Namespace
-                  "domain"          .Values.acs.baseUrl
-                  "k8sdomain"       "cluster.local"
-                  "secure"          (.Values.acs.secure | ternary "s" "")
-                  "realm"           .Values.identity.realm
-                  "directory"
-                    (include "amrc-connectivity-stack.external-url" 
-                      (list . "directory"))
-                | toRawJson | quote }}
-          volumeMounts:
-            - mountPath: /data
-              name: git-checkouts
-        - name: edge-helm-charts
+              env:
+                - name: DIRECTORY_URL
+                  value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
+                - name: SERVICE_USERNAME
+                  value: admin
+                - name: SERVICE_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: admin-password
+                      key: password
+                - name: VERBOSE
+                  value: ALL,!token,!service
+                - name: GIT_CHECKOUTS
+                  value: /data
+                - name: SS_CONFIG
+                  value: {{ .Values.serviceSetup.config | toRawJson | quote }}
+                - name: ACS_CONFIG
+                  value: {{
+                        dict
+                           "organisation"    .Values.acs.organisation
+                           "namespace"       .Release.Namespace
+                           "domain"          .Values.acs.baseUrl
+                           "k8sdomain"       "cluster.local"
+                           "secure"          (.Values.acs.secure | ternary "s" "")
+                           "realm"           .Values.identity.realm
+                           "directory"
+                             (include "amrc-connectivity-stack.external-url"
+                               (list . "directory"))
+                         | toRawJson | quote }}
+              volumeMounts:
+                - mountPath: /data
+                  name: git-checkouts
+            - name: edge-helm-charts
 {{ include "amrc-connectivity-stack.image" (list . .Values.edgeHelm) | indent 10 }}
-          env:
-            - name: DIRECTORY_URL
-              value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
-            - name: SERVICE_USERNAME
-              value: admin
-            - name: SERVICE_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: admin-password
-                  key: password
-            - name: VERBOSE
-              value: ALL,!token,!service
-            - name: GIT_REPO_PATH
-              value: {{ .Values.edgeHelm.repoPath }}
-        - name: manager
-          image: "{{ include "amrc-connectivity-stack.image-name" (list . .Values.manager ) }}-backend"
-          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
-          command: 
-              - /bin/sh
-              - "-c"
-              - |
-                php artisan migrate --force
-                php artisan connections:register
-          env:
-            - name: KRB5_CONFIG
-              value: /config/krb5-conf/krb5.conf
-            - name: MINIO_KEY
-              valueFrom:
-                secretKeyRef:
-                  name: manager-minio-secret
-                  key: CONSOLE_ACCESS_KEY
-            - name: MINIO_SECRET
-              valueFrom:
-                secretKeyRef:
-                  name: manager-minio-secret
-                  key: CONSOLE_SECRET_KEY
-            - name: DB_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: manager-database-secret
-                  key: postgres-password
-            - name: SERVICE_USERNAME
-              value: admin
-            - name: SERVICE_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: admin-password
-                  key: password
-            - name: LOG_LEVEL
-              value: debug
-          envFrom:
-            - configMapRef:
-                name: manager-config
-            - secretRef:
-                name: manager-secrets
-          volumeMounts:
-            - mountPath: /config/keytab
-              name: manager-keytab
-            - mountPath: /config/krb5-conf
-              name: krb5-conf
-            - mountPath: /app/storage/ccache
-              name: manager-ccache-storage
-      containers:
-        - name: restart-mqtt
-          image: bitnami/kubectl:latest
-          command:
-            - /bin/sh
-            - -c
-            - |
-              DEPLOYMENT_NAME=mqtt
-              NAMESPACE={{.Release.Namespace}}
+              env:
+                - name: DIRECTORY_URL
+                  value: http://directory.{{ .Release.Namespace }}.svc.cluster.local
+                - name: SERVICE_USERNAME
+                  value: admin
+                - name: SERVICE_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: admin-password
+                      key: password
+                - name: VERBOSE
+                  value: ALL,!token,!service
+                - name: GIT_REPO_PATH
+                  value: {{ .Values.edgeHelm.repoPath }}
+            - name: manager
+              image: "{{ include "amrc-connectivity-stack.image-name" (list . .Values.manager ) }}-backend"
+              imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
+              command:
+                - /bin/sh
+                - "-c"
+                - |
+                  php artisan migrate --force
+                  php artisan connections:register
+              env:
+                - name: KRB5_CONFIG
+                  value: /config/krb5-conf/krb5.conf
+                - name: MINIO_KEY
+                  valueFrom:
+                    secretKeyRef:
+                      name: manager-minio-secret
+                      key: CONSOLE_ACCESS_KEY
+                - name: MINIO_SECRET
+                  valueFrom:
+                    secretKeyRef:
+                      name: manager-minio-secret
+                      key: CONSOLE_SECRET_KEY
+                - name: DB_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: manager-database-secret
+                      key: postgres-password
+                - name: SERVICE_USERNAME
+                  value: admin
+                - name: SERVICE_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: admin-password
+                      key: password
+                - name: LOG_LEVEL
+                  value: debug
+              envFrom:
+                - configMapRef:
+                    name: manager-config
+                - secretRef:
+                    name: manager-secrets
+              volumeMounts:
+                - mountPath: /config/keytab
+                  name: manager-keytab
+                - mountPath: /config/krb5-conf
+                  name: krb5-conf
+                - mountPath: /app/storage/ccache
+                  name: manager-ccache-storage
+          containers:
+              - name: restart-mqtt
+                image: bitnami/kubectl:latest
+                command:
+                  - /bin/sh
+                  - -c
+                  - |
+                    DEPLOYMENT_NAME=mqtt
+                    NAMESPACE={{.Release.Namespace}}
+                    echo "Attempting to restart deployment: $DEPLOYMENT_NAME"
 
-              echo "Attempting to restart deployment: $DEPLOYMENT_NAME"
+                    # Try to rollout restart the deployment
+                    kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE
 
-              # Try to rollout restart the deployment
-              kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE
-
-              # Wait and check rollout status
-              if kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE --timeout=60s; then
-                echo "Deployment restarted successfully!"
-                exit 0  # Exit successfully, no pod restart needed
-              else
-                echo "Deployment restart failed, retrying..."
-                exit 1  # Exit with error, pod will restart
-              fi
+                    # Wait and check rollout status
+                    if kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE --timeout=60s; then
+                      echo "Deployment restarted successfully!"
+                      exit 0  # Exit successfully, no pod restart needed
+                    else
+                      echo "Deployment restart failed, retrying..."
+                      exit 1  # Exit with error, pod will restart
+                    fi
 ---
 
 apiVersion: v1
